# Configuration options can be accessed as
#   configatron.site_name

development: &local
    site_name: Santhathi
    site_url: http://localhost:3000
    
    company_name: Isiri Technologies Pvt. Ltd.
    admin_email: info@isiritech.com
    
    support_name: Support
    support_email: info@isiritech.com

production:
  <<: *local
  
staging:
  <<: *local

test:
  <<: *local
